# Generated by Django 4.1.5 on 2023-01-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mashine',
        ),
    ]
