# Generated by Django 4.1.5 on 2023-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
